import {
  DARK_MODE_ON,
  DARK_MODE_OFF,
  INIT,
  LOADING,
  LOADING_DONE,
  LOADING_FAILED,
  create,
  getDarkModeToggle,
  setDarkModeToggle,
  getCurrentPage,
  setCurrentPage,
  getJobs,
  setJobs,
  getFilters,
  setFilters,
  getJobDataStatus,
  setJobDataStatus,
  getJobData,
  setJobData,
  isLoading,
} from './state'
import type { State } from './state'

export {
  DARK_MODE_ON,
  DARK_MODE_OFF,
  INIT,
  LOADING,
  LOADING_DONE,
  LOADING_FAILED,
  create,
  getDarkModeToggle,
  setDarkModeToggle,
  getCurrentPage,
  setCurrentPage,
  getJobs,
  setJobs,
  getFilters,
  setFilters,
  getJobDataStatus,
  setJobDataStatus,
  getJobData,
  setJobData,
  isLoading,
}

export type { State }
