import * as Generate from './lib/generate'

import {
  JobType,
  getId,
  setId,
  getPostTime,
  setPostTime,
  getJobType,
  setJobType,
  getTitle,
  setTitle,
  getCompany,
  setCompany,
  getLocation,
  setLocation,
  getAvatarSrc,
  setAvatarSrc,
  getHowToApply,
  setHowToApply,
  getDescription,
  setDescription,
  getCompanyUrl,
  setCompanyUrl,
  create,
} from './lib/domain-jobs'
export {
  JobType,
  getId,
  setId,
  getPostTime,
  setPostTime,
  getJobType,
  setJobType,
  getTitle,
  setTitle,
  getCompany,
  setCompany,
  getLocation,
  setLocation,
  getAvatarSrc,
  setAvatarSrc,
  getHowToApply,
  setHowToApply,
  getDescription,
  setDescription,
  getCompanyUrl,
  setCompanyUrl,
  create,
  Generate,
}

import type { Model } from './lib/domain-jobs'
export type { Model }
